apiVersion: v1
kind: ConfigMap
metadata:
  name: server-001
data:
  config.json: >
    {
      "app_id" : "server-001",
      "app_gid" : "tlsserver",

      "server_ip"   : "12.20.61.1",
      "server_port" : 443,
      "server_ssl"  : 1,

      "stats_ip"   : "172.31.27.11",
      "stats_port" : 30008,

      "send_recv_len" : 1
    }
  
  key.pem: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----

  cert.pem: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----


---


apiVersion: v1
kind: Pod
metadata:
  name: server-001
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "eth0",
              "ips": [ "12.20.61.1/16", "12.20.61.2/16", "12.20.61.3/16",
                       "100.20.61.1/16", "100.20.61.2/16", "100.20.61.3/16"]
            }]'
spec:
  containers:
  - name: server-001
    image: tlspack/tlsperf:latest
    imagePullPolicy: Always
    command: ["tlsserver.exe"]
    args: []
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    volumeMounts:
    - name: config-volume
      mountPath: /configs/
  volumes:
  - name: config-volume
    configMap:
      name: server-001 
  nodeSelector:
    tgid: kube-node2