
apiVersion: v1
kind: Service
metadata:
  name: tlsperf-dev-service2
spec:
  type: NodePort
  selector:
    app: tlsperf-dev
  ports:
    - protocol: TCP
      port: 8887
      targetPort: 8887
      nodePort: 30029
      name: webso
