apiVersion: v1
kind: PersistentVolume
metadata:
  name: tlsperf-dev-volume
  labels:
    type: local
spec:
  storageClassName: manual-dev
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/tlsperf-dev-data"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tlsperf-dev-volume2
  labels:
    type: local
spec:
  storageClassName: manual-dev2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/tlsperf/web"

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tlsperf-dev-pv-claim
spec:
  storageClassName: manual-dev
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tlsperf-dev-pv-claim2
spec:
  storageClassName: manual-dev2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: tlsperf-web-dev-configmap
data:
  config.json: >
    {
      "webui_ip"  : "0.0.0.0",
      "webui_port"  : 8888,

      "stats_port" : 7000,

      "stats_ticks" : 2
    }


---


apiVersion: v1
kind: Pod
metadata:
  name: tlsperf-web-dev
  labels:
    app: tlsperf-web-dev
spec:
  volumes:
    - name: tlsperf-pv-storage
      persistentVolumeClaim:
        claimName: tlsperf-dev-pv-claim
    - name: tlsperf-pv-storage2
      persistentVolumeClaim:
        claimName: tlsperf-dev-pv-claim2
    - name: config-volume
      configMap:
        name: tlsperf-web-dev-configmap
  # serviceAccountName: tlsperf-admin
  containers:
    - name: tlsperf-web-dev
      image: tlspack/tlsperf:latest
      imagePullPolicy: Always
      workingDir: /tlsperf_web/
      command: ["ping"]
      args: ["1.1.1.1"]
      volumeMounts:
        - name: tlsperf-pv-storage
          mountPath: "/data"
        - name: tlsperf-pv-storage2
          mountPath: "/code"
        - name: config-volume
          mountPath: /configs/
  nodeSelector:
    tgid: kube-master


---


apiVersion: v1
kind: Service
metadata:
  name: tlsperf-web-dev-service
spec:
  type: NodePort
  selector:
    app: tlsperf-web-dev
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30027
      name: web
    - protocol: UDP
      port: 7000
      targetPort: 7000
      nodePort: 30028
      name: stats

