apiVersion: v1
kind: Pod
metadata:
  name: tlsclient--{ProfileGroup}--{ProfileName}--{CsGroup}
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            {{ "name": "{ClientIface}",
               "ips": [{ClientIPs}]
            }}]'
spec:
  containers:
  - name: tlsclient--{ProfileGroup}--{ProfileName}--{CsGroup}
    image: tlspack/tlsperf:latest
    imagePullPolicy: Always
    command: [tlsclient.exe]
    args: []
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    volumeMounts:
    - name: config-volume
      mountPath: /configs/
  volumes:
  - name: config-volume
    configMap:
      name: tlsclient--{ProfileGroup}--{ProfileName}--{CsGroup} 

  nodeSelector:
    tgid: {ClientNodeLabel}