apiVersion: v1
kind: Pod
metadata:
  name: tlsserver--{ProfileGroup}--{ProfileName}--{CsGroup}
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "{ServerIface}",
              "ips": [{ServerIPs}]
            }]'
spec:
  containers:
  - name: tlsserver--{ProfileGroup}--{ProfileName}--{CsGroup}
    image: tlspack/tlsperf:latest
    imagePullPolicy: Always
    command: ["tlsserver.exe"]
    args: []
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    volumeMounts:
    - name: config-volume
      mountPath: /configs/
  volumes:
  - name: config-volume
    configMap:
      name: tlsserver--{ProfileGroup}--{ProfileName}--{CsGroup} 
  nodeSelector:
    tgid: {ServerNodeLabel}